title: Food Now
description: 
google_analytics:
show_downloads: false
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github:
  is_project_page: true
  repository_url: https://github.com/food-now/food-now.github.io
gems:
  - jekyll-mentions
